### ISSUE TITLE
Crash due to "get_nb_songs"

### ISSUE THREAD

**Issue by jandechent** [Arn-O/py-kodi-remote-controller#46]
I want to use this script for my RPI, but it crashed right from the first start
python  pykodi.py 127.0.0.1 -p 8080 -u kodi

'Loading the Kodi server library, this may be very long

Traceback (most recent call last):
  File "pykodi.py", line 812, in <module>
    main()
  File "pykodi.py", line 809, in main
    remote_controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "pykodi.py", line 506, in preloop
    get_audio_library(self)
  File "pykodi.py", line 104, in get_audio_library
    get_audio_library_from_server(obj)
  File "pykodi.py", line 138, in get_audio_library_from_server
    nb_songs = get_nb_songs(obj.kodi_params)
NameError: global name 'get_nb_songs' is not defined'

**Comment by Arn-O** [comment]
On it. ;)

**Comment by Arn-O** [comment]
I will fix it shortly.

I have made a major code refactoring today. For a more stable version, you can try:

https://github.com/Arn-O/py-kodi-remote-controller/releases/tag/v0.2.1-alpha

**Comment by Arn-O** [comment]
Note: you do not have to run it on the RPi (I can see the localhost in your command line), you can use it remotely from a Linux box, potentially a Mac. 

Note2: this is under heavy development and any feedback is welcome (bug, issue, feature, usability, documentation, etc.).

**Comment by jandechent** [comment]
Thanks! I stumbled across this project, because I want to assign the buttons of a retro radio to get GPIO of the raspberry. Then I need a command line tool to control KODI. E.g. start/stop volume and start certainl playlists.

**Comment by Arn-O** [comment]
Nice project, I like it!

Regarding the playlist, I use echonest to generate very smart playlist and the result is awesome.
