### ISSUE TITLE
Question: Easy way to pass a command via commandline

### ISSUE THREAD

**Issue by jandechent** [Arn-O/py-kodi-remote-controller#49]
Hey Arn-O,
is there a easy way to execute a command directly upon start?

python pykodi.py 127.0.0.1 -p 8080 -u kodi -vv -c "play_pause"

**Comment by Arn-O** [comment]
There is not. At least currently.

The script is based on the module ``cmd``, which provides a command line interface.

We could imagine the build a separate module of functions or commands to interact with Kodi. The ``cmd`` would just the be UI in this case. PyKodi has not been designed that way, but is not far either.

Ex:
+ command ``play_pause``, described in the function ``do_play_pause`` 
+ use the functions from the external module ``kodi_api``
+ the functions can be used as a standalone (with respect to the required interface)
+ another module could also manage the logic

Not sure to be clear, but in short, all commands could be isolated, and the ``cmd`` would just provide the UI.

**Comment by Arn-O** [comment]
I have just created the ``playback`` in ``pykodi.py``. This function could be moved to a module and this module could be used to create another simple script with the same logic as ``play_pause``.
