### ISSUE TITLE
ERROR:root:too bad, something went wrong!

### ISSUE THREAD

**Issue by kavod** [Arn-O/py-kodi-remote-controller#54]
(Kodi (OpenELEC)) play_album
DEBUG:root:call function do_play_album
DEBUG:root:call function parse_single_int
INFO:root:no album id provided
Album 1490 will be played

DEBUG:root:call function playlist_clear
DEBUG:root:call call_api_http
DEBUG:root:command: {'params': {'playlistid': 0}, 'jsonrpc': '2.0', 'method': 'Playlist.Clear', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 38
DEBUG:root:url: http://192.168.0.10:8080/jsonrpc
DEBUG:root:status code: 200
DEBUG:root:text: {"id":1,"jsonrpc":"2.0","result":"OK"}
DEBUG:root:call display_result
INFO:root:command processed successfully
DEBUG:root:call function playlist_add
DEBUG:root:call call_api_http
DEBUG:root:command: {'params': {'item': {'albumid': 1490}, 'playlistid': 0}, 'jsonrpc': '2.0', 'method': 'Playlist.Add', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 76
DEBUG:root:url: http://192.168.0.10:8080/jsonrpc
DEBUG:root:status code: 200
DEBUG:root:text: {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}
DEBUG:root:call display_result
ERROR:root:too bad, something went wrong!
ERROR:root:error message: Invalid params.
DEBUG:root:call function player_open
DEBUG:root:call call_api_http
DEBUG:root:command: {'params': {'item': {'playlistid': 0}}, 'jsonrpc': '2.0', 'method': 'Player.Open', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 38
DEBUG:root:url: http://192.168.0.10:8080/jsonrpc
DEBUG:root:status code: 200
DEBUG:root:text: {"id":1,"jsonrpc":"2.0","result":"OK"}
DEBUG:root:call display_result
INFO:root:command processed successfully

**Comment by Arn-O** [comment]
Could you try the ``debug_kavod`` function?

Usage: ``kavod_debug 1490``

**Comment by kavod** [comment]
(Kodi (OpenELEC)) debug_kavod  1490

Special debug mode for Kavod library

Length of albums array: 1127

List of IDs: [2048, 2049, 2050, 2051, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 2066, 19, 20, 2069, 2070, 2071, 2072, 2052, 2074, 2075, 2076, 2077, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 2055, 2092, 2093, 2094, 2095, 2096, 2056, 50, 2099, 2100, 2101, 2102, 2057, 2104, 2105, 2106, 2107, 2108, 2058, 62, 63, 2112, 2113, 2114, 67, 68, 69, 2118, 71, 72, 73, 74, 75, 2124, 2125, 2126, 2061, 80, 2129, 2130, 2131, 2132, 2062, 2134, 2063, 2064, 2065, 2067, 2068, 2073, 164, 173, 174, 176, 177, 178, 179, 180, 181, 2079, 2080, 2081, 2082, 2083, 2084, 2053, 2085, 2086, 2087, 2088, 2089, 2054, 2090, 2091, 276, 1987, 295, 296, 2098, 306, 307, 308, 309, 310, 311, 329, 330, 2103, 332, 337, 338, 340, 2109, 2110, 2111, 2059, 2115, 2116, 2117, 425, 2119, 2060, 2120, 2121, 2122, 2123, 461, 2127, 2128, 2133, 593, 648, 673, 705, 724, 759, 760, 761, 762, 763, 765, 766, 767, 768, 770, 771, 772, 773, 774, 775, 777, 778, 779, 780, 781, 782, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 798, 799, 800, 801, 802, 803, 804, 805, 806, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 854, 857, 858, 879, 880, 881, 883, 884, 885, 886, 887, 888, 889, 899, 900, 901, 902, 903, 904, 905, 907, 908, 914, 915, 919, 929, 936, 937, 2078, 971, 1541, 1091, 1092, 1093, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1149, 1152, 1153, 1154, 1155, 1156, 1157, 1163, 1164, 1165, 1166, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1183, 1184, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1230, 1231, 1236, 1238, 1239, 1241, 1242, 1243, 1244, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1273, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1321, 1325, 1331, 1332, 1333, 1340, 1341, 1342, 1343, 1344, 1346, 1347, 1348, 1355, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1387, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 2097, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 331, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047]

DEBUG:__main__:call function parse_single_int
DEBUG:kodi_api:call call_api_http
DEBUG:kodi_api:command: {'params': {'limits': {'start': 1489, 'end': 1490}}, 'jsonrpc': '2.0', 'method': 'AudioLibrary.GetAlbums', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 74
DEBUG:kodi_api:url: http://192.168.0.10:8080/jsonrpc
DEBUG:kodi_api:status code: 200
DEBUG:kodi_api:text: {"id":1,"jsonrpc":"2.0","result":{"limits":{"end":0,"start":0,"total":0}}}
DEBUG:kodi_api:call display_result
INFO:kodi_api:command processed successfully
{u'limits': {u'start': 0, u'total': 0, u'end': 0}}

In the local library: Le Tour de France 88 - France Gall

**Comment by Arn-O** [comment]
I need to write a specific script to understand your library. I guess that there is an issue during the sync process.

**Comment by Arn-O** [comment]
Log for the songs sync:

[kavod1.txt](https://github.com/Arn-O/py-kodi-remote-controller/files/46757/kavod1.txt)

The sync looks fine, but there are gaps in the songids. As a consequence, the index of the song item is different from the ``songid`` which leads to an error with ``songs_page``. Indeed, ``songs_page`` generate a slice of subsequent values, which should be translated into indexes and not read directly as songids.

Since python dictionaries are unordered, a default sorting rule should be applied and the range of indexes should be translated into songids.

Note: the initial issue is related to the ``albums`` data set, but the issue is similar.

**Comment by Arn-O** [comment]
The issue is still open since it does not explain why there is a key 1490 in the ``albums``dataset, but these ``songid`` does not exist in the Kodi library.

**Comment by Arn-O** [comment]
Fixed, or at least unreproducible now.
