### ISSUE TITLE
Can't start py-kodi-remote-controller, crashes after library import

### ISSUE THREAD

**Issue by axelsimon** [Arn-O/py-kodi-remote-controller#61]
Hi there,
When I start pykodi, here's what happens:

```python
python pykodi.py 192.168.0.50 -p 8080 -u xbmc -pw ****

Loading the Kodi server library, this may be very long
Songs: 100% [#############################################################################################] (38308 in 38308) Time: 0:09:06
Traceback (most recent call last):##                                                                         ] (960 in 4120) ETA:  0:01:02
  File "pykodi.py", line 1035, in <module>
    main()
  File "pykodi.py", line 1031, in main
    remote_controller = KodiRemote()
  File "pykodi.py", line 610, in __init__
    get_audio_library(self)
  File "pykodi.py", line 110, in get_audio_library
    get_audio_library_from_server(obj)
  File "pykodi.py", line 240, in get_audio_library_from_server
    obj.albums[album['albumid']]['artist'] = album['artist'][0]
IndexError: list index out of range
```

I've tried several times, with the same result (the import is faster after the first try).

I have a rather large music collection, which may explain this.

Thanks!

axel

**Comment by Arn-O** [comment]
Hi. 

The size is fine and it looks like the songs are loaded properly (which is the largest part of the library).

First thought is that you have an album with an empty artist tag. The script is not able to manage it but should be. 

I'll look into it tomorrow. 

Ar.

**Comment by Arn-O** [comment]
Could you try it now? I can't test this configuration but the modification is simple.

Ar.
